In [128]:
import pandas as pd

In [129]:
d = pd.read_csv('priceoye_laptops_version_2.csv')
d.head()
# data imported successfully

,Unnamed: 0,Name,Discounted Price,Actual Price,Saving,Rating,Reviews,Brand,Core,SSD,Model
0,0,Apple MacBook Air 13 M1 MGN63 (8GB-256GB),203499.0,258000.0,21% OFF,5.0,2.0,Apple,M1,NaN,MacBook Air 13 M1 MGN63
1,1,Apple Macbook Air 13 MW123 M4 Chip,281999.0,350000.0,19% OFF,4.3,5.0,Apple,M4,NaN,Macbook Air 13 MW123 M4 Chip
2,2,ASUS Zenbook 14 UX3405CA Intel Core Ultra 7 25...,285999.0,330000.0,13% OFF,NaN,NaN,ASUS,Ultra 7,16GB-512GB SSD,Zenbook 14 UX3405CA Intel Core Ultra 7 255H
3,3,Lenovo ThinkPad E16 Gen 2 - Intel Core Ultra 7...,287999.0,340000.0,15% OFF,NaN,NaN,Lenovo,Ultra 7,NaN,ThinkPad E16 Gen 2 - Intel Core Ultra 7
4,4,Lenovo IdeaPad Slim 3 Ryzen 7 (8GB-512GB),146999.0,175000.0,16% OFF,NaN,NaN,Lenovo,Ryzen 7,NaN,IdeaPad Slim 3 Ryzen 7

In [130]:
d.shape
# number of imported columns and rows is correct

(306, 11)

In [131]:
d.describe()

       Unnamed: 0  Discounted Price  Actual Price     Rating    Reviews
count  306.000000      3.060000e+02  2.910000e+02  26.000000  26.000000
mean   152.500000      2.775879e+05  3.212616e+05   4.753846   1.615385
std     88.478811      1.708020e+05  1.802598e+05   0.572874   1.134087
min      0.000000      8.599900e+04  1.119990e+05   3.000000   1.000000
25%     76.250000      1.742490e+05  2.000000e+05   5.000000   1.000000
50%    152.500000      2.344990e+05  2.800000e+05   5.000000   1.000000
75%    228.750000      3.449998e+05  3.800000e+05   5.000000   2.000000
max    305.000000      1.552999e+06  1.599900e+06   5.000000   5.000000

In [132]:
d.info()

<class 'pandas.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        306 non-null    int64
 1   Name              306 non-null    str
 2   Discounted Price  306 non-null    float64
 3   Actual Price      291 non-null    float64
 4   Saving            291 non-null    str
 5   Rating            26 non-null     float64
 6   Reviews           26 non-null     float64
 7   Brand             306 non-null    str
 8   Core              219 non-null    str
 9   SSD               92 non-null     str
 10  Model             306 non-null    str
dtypes: float64(4), int64(1), str(6)
memory usage: 26.4 KB

In [133]:
d.dtypes

Unnamed: 0            int64
Name                    str
Discounted Price    float64
Actual Price        float64
Saving                  str
Rating              float64
Reviews             float64
Brand                   str
Core                    str
SSD                     str
Model                   str
dtype: object

In [134]:
d.isna().sum()
# there are 309 missing values in CouponCode

Unnamed: 0            0
Name                  0
Discounted Price      0
Actual Price         15
Saving               15
Rating              280
Reviews             280
Brand                 0
Core                 87
SSD                 214
Model                 0
dtype: int64

In [135]:
d["Actual Price"] = d["Actual Price"].fillna(d["Actual Price"].mean())
d["Rating"] = d["Rating"].fillna(d["Rating"].mean())
d["Reviews"] = d["Reviews"].fillna(d["Reviews"].mean())
d.drop(columns=["Unnamed: 0","Name", "Model"], inplace=True)
d["Core"] = d["Core"].fillna("Unknown")
d["SSD"] = d["SSD"].fillna("Unknown")
d["Saving"] = d["Saving"].str.replace("% OFF", "").str.strip().astype(float)
d["Saving"] = d["Saving"].fillna(d["Saving"].mean())

In [136]:
d.isna().sum()

Discounted Price    0
Actual Price        0
Saving              0
Rating              0
Reviews             0
Brand               0
Core                0
SSD                 0
dtype: int64

In [137]:
d.duplicated().sum()
# 3 duplicates found

np.int64(3)

In [138]:
d.drop_duplicates(inplace=True)
d.duplicated().sum()
# all duplicates removed

np.int64(0)

In [139]:

d["Brand"] = d["Brand"].str.strip().str.title()
d["Core"] = d["Core"].str.strip().str.title()
d["SSD"] = d["SSD"].str.strip()

d["Discounted Price"] = pd.to_numeric(d["Discounted Price"], errors="coerce")
d["Actual Price"] = pd.to_numeric(d["Actual Price"], errors="coerce")

d.reset_index(drop=True, inplace=True)
d.head()

,Discounted Price,Actual Price,Saving,Rating,Reviews,Brand,Core,SSD
0,203499.0,258000.0,21.0,5.000000,2.000000,Apple,M1,Unknown
1,281999.0,350000.0,19.0,4.300000,5.000000,Apple,M4,Unknown
2,285999.0,330000.0,13.0,4.753846,1.615385,Asus,Ultra 7,16GB-512GB SSD
3,287999.0,340000.0,15.0,4.753846,1.615385,Lenovo,Ultra 7,Unknown
4,146999.0,175000.0,16.0,4.753846,1.615385,Lenovo,Ryzen 7,Unknown